# Generated by Django 4.0 on 2024-03-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('opening_date', models.DateField()),
                ('running_time', models.IntegerField()),
                ('over_view', models.TextField()),
            ],
        ),
    ]
