# Generated by Django 4.0 on 2024-03-14 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='over_view',
            new_name='overview',
        ),
    ]
